# Generated by Django 5.0 on 2024-01-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_country_alter_user_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
