# Generated by Django 5.0 on 2023-12-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(default='blog_preview/default.png', upload_to='blog_preview/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
