# Generated by Django 5.0 on 2023-12-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview_image',
            field=models.ImageField(default='product_preview/default.svg', upload_to='product_preview/', verbose_name='Фото товара(превью)'),
        ),
    ]
